### ISSUE TITLE
bug or feature?

### ISSUE THREAD

**Issue by vectorsize** [Ircam-RnD/biquad-filter#1]
should'nt [this line](https://github.com/Ircam-RnD/biquad-filter/blob/master/index.js#L176) be

```
this.memories[p].yi1 = y[p] * this.coefficients.g;
```

instead of

```
this.memories[p].yi1 = y[p];
```

**Comment by narnau** [comment]
As fas as I know the code is correct. In this line, the memory is updated, so the y[n] position is copied to the y[n-1] position.

The gain is applied in [this line](https://github.com/Ircam-RnD/biquad-filter/blob/master/index.js#L168). Thus, the gain is applied to the output, as expected.
